version: '3'
services:
  simple-warehouse-api-db:
    image: postgres:12
    restart: always
    ports:
      - "5443:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: simple-warehouse-api